version: '3'

services: 
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /usr/app/client/node_modules
            - /client:/usr/app/client